### ISSUE TITLE
Set max-width on desktop

### ISSUE THREAD

**Issue by rayshan** [edlea/DesktopAMP#5]
On a 2560x1440 monitor, this isn't a great experience:

![screen shot 2015-10-14 at 12 25 13 pm](https://cloud.githubusercontent.com/assets/3760840/10495116/03543b86-726f-11e5-97b6-53b0621a0e53.png)

This is better:

![screen shot 2015-10-14 at 12 27 26 pm](https://cloud.githubusercontent.com/assets/3760840/10495120/0855ea80-726f-11e5-9a38-e239c6b02eed.png)

**Comment by edlea** [comment]
Agreed. However, the current behaviour is to load the AMP URL directly in the browser, unmodified. Some sites specify max-width, others don't.

The choice is to either modify the HTML or load the page in an iframe with a fixed width. I'm not sure which is better...

**Comment by edlea** [comment]
I've set all immediate children of the body tag to have `max-width of 600px` and `margin: 0px auto` on pages with the ⚡️ or `amp` attribute in the `<html>` tag

**Comment by rayshan** [comment]
:tada: That's a good reading width! Thanks!
