### ISSUE TITLE
Seems to mess with back button on The Verge

### ISSUE THREAD

**Issue by andybak** [edlea/DesktopAMP#8]
1. Start at https://github.com/edlea/DesktopAMP
2. Click on link to the verge at the bottom
3. click on an article
4. click back.

You're now back at Github instead of the Verge home page

**Comment by edlea** [comment]
I'm not able to reproduce this on either Chrome or Safari. Not every Verge article seems to be AMP-ready for some reason, but [Apple developing advanced display tech at Taiwan lab: report](http://www.theverge.com/platform/amp/2015/12/14/10160654/apple-display-tech-development-taiwan-oled-lcd) does and when I go back I'm back at theverge.com
