### ISSUE TITLE
Setting max-width doesn't always work correctly.

### ISSUE THREAD

**Issue by vrwarp** [edlea/DesktopAMP#9]
Example URL (scroll to the bottom): http://www.buzzfeed.com/amphtml/ailbhemalone/things-i-wish-id-known-about-money-in-my-twenties

What is happening is the list on the bottom sets the following style: margin-right: 0.5rem which is overriding the margin: 0 auto. One hacky way to "fix" it is to set margin: 0 auto !important but I think the real right way to fix this is to create a container and hoist all the content of the body into the container and set the container's max width to 600px. That way any margins set by the original site will work correctly.

**Comment by rayshan** [comment]
Here's another page which max-width doesn't work at all on:

https://www.yahoo.com/amphtml/tech/s/danielle-morrill-mattermark-ceo-early-120003385.html

**Comment by edlea** [comment]
Both issues are fixed in #13
